### ISSUE TITLE
obs-midi crashes OBS if I set bidirectional for a midi event row.

### ISSUE THREAD

**Issue by takyano** [Alzy/obs-midi#18]
Windows 10
OBS-Studio-25.0.8
obs-midi-109e8c6
obs-virtualcam-2.0.5
obs-websocket-4.8.0

Setting bidirectional checkbox in obs-midi device midi configuration page can cause a crash and corruption of the [MidiAPI] midi_devices entry in basic.ini

1. Open the OBS MIDI Setting dialog.
2. Select a device and press Configure.
3. Press a button.
4. Change it from Fader to Button,
5. Turn on bidirectional for that button
6. Save
7. Press that button to select that scene.
8. Crash OBS

**Comment by cpyarger** [comment]
Sorry, That ui feature needs to be removed. Bidirectional is being handled in the window before it and that was a remanent

**Comment by cpyarger** [comment]
The Latest release should take care of that

**Comment by takyano** [comment]
may as well close this.

checkbox is gone.

that can't be the cause of a crash now. :)

**Comment by cpyarger** [comment]
Fair point (:
