### ISSUE TITLE
Multiple entries for one midi controller in basic.ini

### ISSUE THREAD

**Issue by takyano** [Alzy/obs-midi#19]
I am having issues where I get multiple entries for a MIDI controller in basic.ini,
I have tried this with the Native Instruments Kontrol F1 and a Roland A-01.

If i remove the midi_devices filed from basic.ini and watch the file as I use OBS:

Testing with the Roland A-01.

Open the the OBS MIDI setting dialog
Select a MIDI Controller from the list.
basic.ini is updated with the entry for the device with the first item in the list added as the output device.

Select a different MIDI controller for output
basic.ini is updated.

Close the dialog and close OBS.
Only the one entry for the device.

Reopen OBS.
Open the the OBS MIDI setting dialog
Select the MIDI Controller from the list.
The Output setting a made before is ignored and the first item on the list is selected.
basic.ini is updated with that device.

Select a different MIDI controller for output
basic.ini is updated.

Close the dialog and close OBS.
Only the one entry for the device.

Reopen OBS.

Open the the OBS MIDI setting dialog
Select the MIDI Controller from the list.
The Output setting a made before is ignored and the first item on the list is selected.
basic.ini is updated with that device.

Press Configure
Press a keyboard key to get a note on and note off entry.
Close the dialog and close OBS.

I now have 2 entries for the device under MidiAPI MidiDevices.
One with no hooks and one with hooks.

This can cause several problems:

1. Crash to OBS's Crashlog dialog on saving and closing the Confiure dialog.
2. Crash to OBS's Crashlog dialog on pressing that button.
3. all actions are gone in the configuration for the device on reopening OBS.

**Comment by Alzy** [comment]
pushed an update just now that MIGHT have fixed this issue. In any case, please delete any broken basic.ini files before installing. Open a new issue if the problem persists
