### ISSUE TITLE
Transitions

### ISSUE THREAD

**Issue by skylergreene** [Alzy/obs-midi#24]
It would make this plugin so much more powerful if I could midi map a button, fader, or knob to cue preset transitions.
Additionally, it would be great to use a fader or knob to adjust the "Quick Transitions" slider.
Lastly, it would be useful to be able to configure a knob or fader to change the duration of the transition.
It would also be useful to be able to configure a button to change the transition duration to preset values.

**Comment by cpyarger** [comment]
Should be in the latest release https://github.com/cpyarger/obs-midi/releases/latest
