### ISSUE TITLE
Show/Hide/Toggle Sources & Filters

### ISSUE THREAD

**Issue by skylergreene** [Alzy/obs-midi#25]
It would be great to be able to be able to show, hide, and toggle sources & filters with midi control.

**Comment by countdookuw** [comment]
Also please add show/hide/toggle for groups.

**Comment by Croniac** [comment]
Toggle Source would be especially useful, right now I am using Midi2Key to get a hot key from midi to accomplish this, would much prefer to see it all in OBS-Midi.

**Comment by exerkaoss** [comment]
it works very good beside some here and then crashes but features from midi2obs are truly missing, especially when streaming without a stgreamdeck or deckboard. 
with a novation launchpad or akai lpd, could be triggered those sources.
Thank you so much for makin this

**Comment by cpyarger** [comment]
I believe this is in the latest release https://github.com/cpyarger/obs-midi/releases/latest
