### ISSUE TITLE
Not loading DLL

### ISSUE THREAD

**Issue by cpyarger** [Alzy/obs-midi#26]
From https://obsproject.com/forum/threads/obs-midi.125232/page-2#post-477226

> Thank you. Successfully installed but when I start OBS, there is no Midi option under Tools.
> I verified that OBS-Midi files are in the correct Plugins folder (64bit).
> I attached screen shots and here is a portion of the OBS logfile.

```
[CoreAudio encoder]: CoreAudio AAC encoder not installed on the system or couldn't be loaded
13:41:55.160: Failed to load 'en-US' text for module: 'decklink-ouput-ui.dll'
13:41:55.245: [AMF] Unable to load 'amfrt64.dll', error code 126.
13:41:55.262: [AMF] AMF Test failed due to one or more errors.
13:41:55.262: Failed to initialize module 'enc-amf.dll'
13:41:56.521: [obs-browser]: Version 2.8.6
13:41:56.721: LoadLibrary failed for '../../obs-plugins/64bit/obs-midi.dll': The specified module could not be found.
13:41:56.721: (126)
13:41:56.721: Module '../../obs-plugins/64bit/obs-midi.dll' not loaded
13:41:57.082: Couldn't find VLC installation, VLC video source disabled
13:41:57.158: A DeckLink iterator could not be created. The DeckLink drivers may not be installed
13:41:57.159: No blackmagic support
```

![image](https://user-images.githubusercontent.com/1778298/90966143-f5e9e900-e49c-11ea-8c1e-d96a6f34630c.png)
![image](https://user-images.githubusercontent.com/1778298/90966145-faae9d00-e49c-11ea-9016-294e974b0f17.png)
 

Installed with latest OBS

**Comment by solarboogie** [comment]
I had the same issue. I solved it by installing the 'all in one' C++ redistributable found here: https://www.techpowerup.com/download/visual-c-redistributable-runtime-package-all-in-one/
I am sure I didn't have to install all the runtimes, but I don't know exactly which one this dll needs so I installed them all.
Jon
