### ISSUE TITLE
OBS crashes if not in studio mode and set preview scene button is triggered

### ISSUE THREAD

**Issue by countdookuw** [Alzy/obs-midi#27]
Set Preview Scene works fine in studio mode as expected but will crash OBS if you switch to simple mode and trigger your preview button as there is no preview window in that mode. 

Also Set Scene lights up the button of the active scene on my Beringer xtouch mini but not Set Preview Scene - the button lights up and turns back off for preview but stays lit for Set Scene which is handy to know which scene is active.

**Comment by rmihai81** [comment]
Same!!!Now my OBS not star up.:((

**Comment by countdookuw** [comment]
If that happens and you are using Windows go into the task manager and search for obs in the processes and end the one named obs. It should start up then.
