### ISSUE TITLE
Midi button mapping missing

### ISSUE THREAD

**Issue by countdookuw** [Alzy/obs-midi#29]
I set up about 16 button mappings using the utility, saved and tested by closing OBS and opening it to see if everything stayed when last night it was all working. My computer must have gone to sleep overnight and when I fired it up and started OBS now all the button mappings are gone. I'm not sure where the config file is stored or how to open it to verify if it still has the mappings somewhere. I tried closing OBS and restarting but still no mappings.

**Comment by cpyarger** [comment]
The config is stored in the obs config file 

Windows: WinKey+R > %APPDATA%\obs-studio.
macOS: Cmd+Shift+G > ~/Library/Application Support/obs-studio.
Linux: ~/. config/obs-studio.

under those directory there should should be something like /basic/profiles/Untitled/basic.ini

The full path for mine on windows is 
C:\Users\cpyar\AppData\Roaming\obs-studio\basic\profiles\Untitled\basic.ini

**Comment by countdookuw** [comment]
Thanks - I was having a tough time finding it. 

Here is the midi part. I'm assuming if I back this up and copy paste in the data when it goes missing it may work? 

Should the "Bidirectional" and "hooks" lines be showing up multiple times like they do? I wonder if several iterations adding buttons and hitting save screwed things up? I'm really rusty on my programming/debugging. 

[MidiAPI]
DebugEnabled=false
AlertsEnabled=true
MidiDevices={\n    "devices": [\n        {\n            "bidirectional": false,\n            "enabled": true,\n            "hooks": [\n                {\n                    "action": "Set Current Scene",\n                    "command": "Set Current Scene",\n                    "index": 16,\n                    "mchan": 11,\n                    "param1": "Powerpoint overlay UL",\n                    "param2": "",\n                    "param3": "",\n                    "type": "note_on"\n                },\n                {\n                    "action": "Set Mute",\n                    "command": "Set Mute",\n                    "index": 16,\n                    "mchan": 11,\n                    "param1": "Mic/Aux",\n                    "param2": "",\n                    "param3": "",\n                    "type": "note_off"\n                },\n                {\n                    "action": "Set Current Scene",\n                    "command": "Set Current Scene",\n                    "index": 17,\n                    "mchan": 11,\n                    "param1": "Start/Stop View",\n                    "param2": "",\n                    "param3": "",\n                    "type": "note_on"\n                },\n                {\n                    "action": "Set Current Scene",\n                    "command": "Set Current Scene",\n                    "index": 17,\n                    "mchan": 11,\n                    "param1": "Start/Stop View",\n                    "param2": "",\n                    "param3": "",\n                    "type": "note_off"\n                },\n                {\n                    "action": "Set Volume",\n                    "command": "Set Volume",\n                    "index": 1,\n                    "mchan": 11,\n                    "param1": "Mic/Aux",\n                    "param2": "",\n                    "param3": "",\n                    "type": "control_change"\n                }\n            ],\n            "name": "X-TOUCH MINI 1",\n            "outname": "X-TOUCH MINI 1"\n        },\n        {\n            "bidirectional": false,\n            "enabled": true,\n            "hooks": [\n                {\n                    "action": "Set Volume",\n                    "command": "Set Volume",\n                    "index": 1,\n                    "mchan": 11,\n                    "param1": "Mic/Aux",\n                    "param2": "",\n                    "param3": "",\n                    "type": "control_change"\n                },\n                {\n                    "action": "Set Volume",\n                    "command": "Set Volume",\n                    "index": 2,\n                    "mchan": 11,\n                    "param1": "Desktop Audio",\n                    "param2": "",\n                    "param3": "",\n                    "type": "control_change"\n                },\n                {\n                    "action": "Toggle Mute",\n                    "command": "Toggle Mute",\n                    "index": 0,\n                    "mchan": 11,\n                    "param1": "Mic/Aux",\n                    "param2": "",\n                    "param3": "",\n                    "type": "note_on"\n                },\n                {\n                    "action": "Toggle Mute",\n                    "command": "Toggle Mute",\n                    "index": 1,\n                    "mchan": 11,\n                    "param1": "Desktop Audio",\n                    "param2": "",\n                    "param3": "",\n                    "type": "note_on"\n                }\n            ],\n            "name": "X-TOUCH MINI 1",\n            "outname": "X-TOUCH MINI 1"\n        },\n        {\n            "bidirectional": false,\n            "enabled": true,\n            "hooks": [\n                {\n                    "action": "Set Current Scene",\n                    "command": "Set Current Scene",\n                    "index": 16,\n                    "mchan": 11,\n                    "param1": "Powerpoint overlay UL",\n                    "param2": "",\n                    "param3": "",\n                    "type": "note_on"\n                },\n                {\n                    "action": "Set Current Scene",\n                    "command": "Set Current Scene",\n                    "index": 16,\n                    "mchan": 11,\n                    "param1": "Powerpoint overlay UL",\n                    "param2": "",\n                    "param3": "",\n                    "type": "note_off"\n                },\n                {\n                    "action": "Set Current Scene",\n                    "command": "Set Current Scene",\n                    "index": 17,\n                    "mchan": 11,\n                    "param1": "Powerpoint Only",\n                    "param2": "",\n                    "param3": "",\n                    "type": "note_on"\n                },\n                {\n                    "action": "Set Current Scene",\n                    "command": "Set Current Scene",\n                    "index": 17,\n                    "mchan": 11,\n                    "param1": "Powerpoint Only",\n                    "param2": "",\n                    "param3": "",\n                    "type": "note_off"\n                },\n                {\n                    "action": "Set Volume",\n                    "command": "Set Volume",\n                    "index": 1,\n                    "mchan": 11,\n                    "param1": "Mic/Aux",\n                    "param2": "",\n                    "param3": "",\n                    "type": "control_change"\n                },\n                {\n                    "action": "Set Volume",\n                    "command": "Set Volume",\n                    "index": 2,\n                    "mchan": 11,\n                    "param1": "Desktop Audio",\n                    "param2": "",\n                    "param3": "",\n                    "type": "control_change"\n                },\n                {\n                    "action": "Toggle Mute",\n                    "command": "Toggle Mute",\n                    "index": 0,\n                    "mchan": 11,\n                    "param1": "Mic/Aux",\n                    "param2": "",\n                    "param3": "",\n                    "type": "note_on"\n                },\n                {\n                    "action": "Toggle Mute",\n                    "command": "Toggle Mute",\n                    "index": 1,\n                    "mchan": 11,\n                    "param1": "Desktop Audio",\n                    "param2": "",\n                    "param3": "",\n                    "type": "note_on"\n                },\n                {\n                    "action": "Set Current Scene",\n                    "command": "Set Current Scene",\n                    "index": 18,\n                    "mchan": 11,\n                    "param1": "Camera Only",\n                    "param2": "",\n                    "param3": "",\n                    "type": "note_on"\n                },\n                {\n                    "action": "Set Current Scene",\n                    "command": "Set Current Scene",\n                    "index": 18,\n                    "mchan": 11,\n                    "param1": "Camera Only",\n                    "param2": "",\n                    "param3": "",\n                    "type": "note_off"\n                },\n                {\n                    "action": "Set Current Scene",\n                    "command": "Set Current Scene",\n                    "index": 19,\n                    "mchan": 11,\n                    "param1": "Start/Stop View",\n                    "param2": "",\n                    "param3": "",\n                    "type": "note_on"\n                },\n                {\n                    "action": "Set Current Scene",\n                    "command": "Set Current Scene",\n                    "index": 19,\n                    "mchan": 11,\n                    "param1": "Start/Stop View",\n                    "param2": "",\n                    "param3": "",\n                    "type": "note_off"\n                },\n                {\n                    "action": "Set Current Scene",\n                    "command": "Set Current Scene",\n                    "index": 20,\n                    "mchan": 11,\n                    "param1": "DVD Desktop 2",\n                    "param2": "",\n                    "param3": "",\n                    "type": "note_on"\n                },\n                {\n                    "action": "Set Current Scene",\n                    "command": "Set Current Scene",\n                    "index": 20,\n                    "mchan": 11,\n                    "param1": "DVD Desktop 2",\n                    "param2": "",\n                    "param3": "",\n                    "type": "note_off"\n                }\n            ],\n            "name": "X-TOUCH MINI 1",\n            "outname": "X-TOUCH MINI 1"\n        },\n        {\n            "bidirectional": false,\n            "enabled": true,\n            "hooks": [\n                {\n                    "action": "Set Volume",\n                    "command": "Set Volume",\n                    "index": 1,\n                    "mchan": 11,\n                    "param1": "Mic/Aux",\n                    "param2": "",\n                    "param3": "",\n                    "type": "control_change"\n                },\n                {\n                    "action": "Set Volume",\n                    "command": "Set Volume",\n                    "index": 2,\n                    "mchan": 11,\n                    "param1": "Desktop Audio",\n                    "param2": "",\n                    "param3": "",\n                    "type": "control_change"\n                },\n                {\n                    "action": "Toggle Mute",\n                    "command": "Toggle Mute",\n                    "index": 0,\n                    "mchan": 11,\n                    "param1": "Mic/Aux",\n                    "param2": "",\n                    "param3": "",\n                    "type": "note_on"\n                },\n                {\n                    "action": "Toggle Mute",\n                    "command": "Toggle Mute",\n                    "index": 1,\n                    "mchan": 11,\n                    "param1": "Desktop Audio",\n                    "param2": "",\n                    "param3": "",\n                    "type": "note_on"\n                }\n            ],\n            "name": "X-TOUCH MINI 1",\n            "outname": "X-TOUCH MINI 1"\n        },\n        {\n            "bidirectional": false,\n            "enabled": true,\n            "hooks": [\n                {\n                    "action": "Set Current Scene",\n                    "command": "Set Current Scene",\n                    "index": 16,\n                    "mchan": 11,\n                    "param1": "Powerpoint overlay UL",\n                    "param2": "",\n                    "param3": "",\n                    "type": "note_on"\n                },\n                {\n                    "action": "Set Mute",\n                    "command": "Set Mute",\n                    "index": 16,\n                    "mchan": 11,\n                    "param1": "Mic/Aux",\n                    "param2": "",\n                    "param3": "",\n                    "type": "note_off"\n                }\n            ],\n            "name": "X-TOUCH MINI 1",\n            "outname": "X-TOUCH MINI 1"\n        },\n        {\n            "bidirectional": false,\n            "enabled": true,\n            "hooks": [\n                {\n                    "action": "Set Volume",\n                    "command": "Set Volume",\n                    "index": 1,\n                    "mchan": 11,\n                    "param1": "Mic/Aux",\n                    "param2": "",\n                    "param3": "",\n                    "type": "control_change"\n                },\n                {\n                    "action": "Set Volume",\n                    "command": "Set Volume",\n                    "index": 2,\n                    "mchan": 11,\n                    "param1": "Desktop Audio",\n                    "param2": "",\n                    "param3": "",\n                    "type": "control_change"\n                },\n                {\n                    "action": "Toggle Mute",\n                    "command": "Toggle Mute",\n                    "index": 0,\n                    "mchan": 11,\n                    "param1": "Mic/Aux",\n                    "param2": "",\n                    "param3": "",\n                    "type": "note_on"\n                },\n                {\n                    "action": "Toggle Mute",\n                    "command": "Toggle Mute",\n                    "index": 1,\n                    "mchan": 11,\n                    "param1": "Desktop Audio",\n                    "param2": "",\n                    "param3": "",\n                    "type": "note_on"\n                }\n            ],\n            "name": "X-TOUCH MINI 1",\n            "outname": "X-TOUCH MINI 1"\n        },\n        {\n            "bidirectional": false,\n            "enabled": true,\n            "hooks": [\n                {\n                    "action": "Set Current Scene",\n                    "command": "Set Current Scene",\n                    "index": 16,\n                    "mchan": 11,\n                    "param1": "Powerpoint overlay UL",\n                    "param2": "",\n                    "param3": "",\n                    "type": "note_on"\n                },\n                {\n                    "action": "Set Current Scene",\n                    "command": "Set Current Scene",\n                    "index": 16,\n                    "mchan": 11,\n                    "param1": "Powerpoint overlay UL",\n                    "param2": "",\n                    "param3": "",\n                    "type": "note_off"\n                },\n                {\n                    "action": "Set Current Scene",\n                    "command": "Set Current Scene",\n                    "index": 17,\n                    "mchan": 11,\n                    "param1": "Powerpoint Only",\n                    "param2": "",\n                    "param3": "",\n                    "type": "note_on"\n                },\n                {\n                    "action": "Set Current Scene",\n                    "command": "Set Current Scene",\n                    "index": 17,\n                    "mchan": 11,\n                    "param1": "Powerpoint Only",\n                    "param2": "",\n                    "param3": "",\n                    "type": "note_off"\n                },\n                {\n                    "action": "Set Volume",\n                    "command": "Set Volume",\n                    "index": 1,\n                    "mchan": 11,\n                    "param1": "Mic/Aux",\n                    "param2": "",\n                    "param3": "",\n                    "type": "control_change"\n                },\n                {\n                    "action": "Set Volume",\n                    "command": "Set Volume",\n                    "index": 2,\n                    "mchan": 11,\n                    "param1": "Desktop Audio",\n                    "param2": "",\n                    "param3": "",\n                    "type": "control_change"\n                },\n                {\n                    "action": "Toggle Mute",\n                    "command": "Toggle Mute",\n                    "index": 0,\n                    "mchan": 11,\n                    "param1": "Mic/Aux",\n                    "param2": "",\n                    "param3": "",\n                    "type": "note_on"\n                },\n                {\n                    "action": "Toggle Mute",\n                    "command": "Toggle Mute",\n                    "index": 1,\n                    "mchan": 11,\n                    "param1": "Desktop Audio",\n                    "param2": "",\n                    "param3": "",\n                    "type": "note_on"\n                },\n                {\n                    "action": "Set Current Scene",\n                    "command": "Set Current Scene",\n                    "index": 18,\n                    "mchan": 11,\n                    "param1": "Camera Only",\n                    "param2": "",\n                    "param3": "",\n                    "type": "note_on"\n                },\n                {\n                    "action": "Set Current Scene",\n                    "command": "Set Current Scene",\n                    "index": 18,\n                    "mchan": 11,\n                    "param1": "Camera Only",\n                    "param2": "",\n                    "param3": "",\n                    "type": "note_off"\n                },\n                {\n                    "action": "Set Current Scene",\n                    "command": "Set Current Scene",\n                    "index": 19,\n                    "mchan": 11,\n                    "param1": "Start/Stop View",\n                    "param2": "",\n                    "param3": "",\n                    "type": "note_on"\n                },\n                {\n                    "action": "Set Current Scene",\n                    "command": "Set Current Scene",\n                    "index": 19,\n                    "mchan": 11,\n                    "param1": "Start/Stop View",\n                    "param2": "",\n                    "param3": "",\n                    "type": "note_off"\n                },\n                {\n                    "action": "Set Current Scene",\n                    "command": "Set Current Scene",\n                    "index": 20,\n                    "mchan": 11,\n                    "param1": "DVD Desktop 2",\n                    "param2": "",\n                    "param3": "",\n                    "type": "note_on"\n                },\n                {\n                    "action": "Set Current Scene",\n                    "command": "Set Current Scene",\n                    "index": 20,\n                    "mchan": 11,\n                    "param1": "DVD Desktop 2",\n                    "param2": "",\n                    "param3": "",\n                    "type": "note_off"\n                }\n            ],\n            "name": "X-TOUCH MINI 1",\n            "outname": "X-TOUCH MINI 1"\n        },\n        {\n            "bidirectional": false,\n            "enabled": true,\n            "hooks": [\n                {\n                    "action": "Set Volume",\n                    "command": "Set Volume",\n                    "index": 1,\n                    "mchan": 11,\n                    "param1": "Mic/Aux",\n                    "param2": "",\n                    "param3": "",\n                    "type": "control_change"\n                },\n                {\n                    "action": "Set Volume",\n                    "command": "Set Volume",\n                    "index": 2,\n                    "mchan": 11,\n                    "param1": "Desktop Audio",\n                    "param2": "",\n                    "param3": "",\n                    "type": "control_change"\n                },\n                {\n                    "action": "Toggle Mute",\n                    "command": "Toggle Mute",\n                    "index": 0,\n                    "mchan": 11,\n                    "param1": "Mic/Aux",\n                    "param2": "",\n                    "param3": "",\n                    "type": "note_on"\n                },\n                {\n                    "action": "Toggle Mute",\n                    "command": "Toggle Mute",\n                    "index": 1,\n                    "mchan": 11,\n                    "param1": "Desktop Audio",\n                    "param2": "",\n                    "param3": "",\n                    "type": "note_on"\n                }\n            ],\n            "name": "X-TOUCH MINI 1",\n            "outname": "X-TOUCH MINI 1"\n        }\n    ]\n}

**Comment by cpyarger** [comment]
To be honest, I can't remember how that configuration code is set up.  The
new system is being designed to prevent duplicates and other configuration
related issues out of the box.  I believe that configuration code was
written by Alzy though so me may be able to tell you ☺️

**Comment by Alzy** [comment]
It looks like your ini file is indeed broken.  You should delete the MidiDevices variable in it and start over. I just pushed a fix that might help with the issue. Not sure how to release it following the previous pipeline but a build will be out soon.

**Comment by cpyarger** [comment]
Have a look at the latest build, please note that existing mappings should be deleted before running the new build https://github.com/cpyarger/obs-midi/releases/latest
