### ISSUE TITLE
Allow manual defining of output codes

### ISSUE THREAD

**Issue by MTRNord** [Alzy/obs-midi#30]
Hi I have the original Launchpad S and the LaunchControl. Both use different output codes to toggle the colors of buttons. It would be nice to either map those or allow manual setting of them to indicate where I left of :)

**Comment by MTRNord** [comment]
hm actually it seems to sometimes work but sometimes not. Might just be a issue that it not always does work

**Comment by MTRNord** [comment]
So the Launchpad S seems to show colors but the Launch Control does not. Also bidirectional does not keep checked

**Comment by rockumk** [comment]
Same here. :) I love this project. It wasn't stable under mac OS for me, but when it worked it was so nice and the interface is really nice.
