### ISSUE TITLE
OBS-midi crashing OBS on mac because of devices duplicate in basic.in - Solution inside

### ISSUE THREAD

**Issue by XReyRobert** [Alzy/obs-midi#32]
OBS-MIDI on Mac

I've been experiencing a lot of crashes and developer seems to be aware of the mac issues, but I just wanted to quickly share back how to make it work. Dev said he's rewriting all plugin so I didn't investigate into source code to fix this.

The issues on mac comes from the fact that the device configuration gets duplicated in OBS basic.ini

The MidiDevices JSON array gets messy when clicking the save button as device configuration is not overridden but device is duplicated with new configuration.

To solve this you (and backup your midi settings too) can go and tweak the JSON:
here : ~/Library/Application Support/obs-studio/basic/profiles/[YOURPROFILENAME]/basic.ini

I would recommend to start clean. Do one and only configuration through the app to discover your midi inputs and then go to the basic.ini configuration file if you need to change anything to the configuration.

No OBS crash when proceeding this way so way...

Hope it helps some of you.

**Comment by rockumk** [comment]
@XReyRobert  Could you explain in a bit more detail how to do the work around? Thanks.

**Comment by pascalandy** [comment]
I little video would be nice :)

I'm using MidiShortcut and it's fine. But when OBS instance is not active, the hotkeys doesn't work anymore.

**Comment by aoraion** [comment]
@XReyRobert I can find the file, but you're going to have to explain what "tweak" means. Any help is greatly appreciated!

**Comment by cpyarger** [comment]
Are you still having the same issue on the latest release found here ? https://github.com/cpyarger/obs-midi/releases/latest

**Comment by cpyarger** [comment]
Config Files have just received a major update, All duplicate issues have been solved new releases are [here](https://github.com/cpyarger/obs-midi/releases/latest)
