### ISSUE TITLE
Request: Midi CC-control of Transition Fader (in studio-mode)

### ISSUE THREAD

**Issue by drumbliss** [Alzy/obs-midi#33]
Didn't find another post requesting this, but I know from the OBSproject.com page comments that I'm sharing this request with others. It is the most important reason for me personally to pursue MIDI control of OBS.
Thanks for your great and important work!

**Comment by TheNeverEndingEcksDee** [comment]
+1 on this one, thanks!

**Comment by vulgerrity** [comment]
+1!  Would absolutely love to see this.

**Comment by redfox2492** [comment]
Yes! this would be great!

**Comment by cpyarger** [comment]
This has been implemented in the latest release found here https://github.com/cpyarger/obs-midi/releases/latest
