### ISSUE TITLE
Triggering Set Mute action causes OBS to crash

### ISSUE THREAD

**Issue by WillPJK** [Alzy/obs-midi#35]
Wonderful tool; I'm very much looking forward to seeing the results of the rewrite! Thank you so so much for the time being put into this.

This bug might simply be due to the way I set things up, but I am consistently having OBS crash* when a note on or off action tries to Set Mute.

I'm honestly not sure what Set Mute is supposed to do and Toggle Mute was the action I was actually looking for, but thought I should report the bug as, even if it's just PEBCAK, it's causing a complete program crash.

OBS seems to carry on as normal behind the crash notice, but dismissing the note brings the whole thing down.

*Unhandled exception: e06d7363
Fault address: 7FFA22103E49 (c:\windows\system32\kernelbase.dll, libobs version: 26.0.0 (64-bit)
Windows version: 10.0 build 19041 (release: 2004; revision: 508; 64-bit)
Happy to provide further info from crash log directly if required)

**Comment by cpyarger** [comment]
apologies, set mute should be hidden until we have the ability to pass a user-defined bool along with it.

**Comment by cpyarger** [comment]
The difference between set mute, and toggle mute is set mute is setting a distinct state, where toggle mute toggles back and forth between muted and not muted.
