### ISSUE TITLE
can you help me with install procedure please

### ISSUE THREAD

**Issue by Luxcium** [Alzy/obs-midi#39]
I am sorry I don't know how to `Append to CMakeLists.txt`

**Comment by Luxcium** [comment]
Should I put  `obs-midi` in */`${home}`/obs-studio-portable/obs-plugins/**obs-midi/*** or in */`${home}`/obs-studio-portable/**data**/obs-plugins/**obs-midi/***

**Comment by Alzy** [comment]
@Luxcium are you trying to install for development purposes? or just to use the plugin?
