### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by obsbuddy** [Alzy/obs-midi#44]
Hello, great little plug-in. It cancels out the MidiKey2Key, so I was wondering if you could include some of the features from that app so that I could add LED feedback to my apc mini, just by using your plugin, OR be able to use both the plugin and the app together with the SAME controller. In any case, being able to have multi-coloured feedback as off, yellow, green or red is what i'm hoping for.

I would really like to see the Transition and Quick Transitions in this, and being able to map the transition fader. I'm also interested in the Mute buttons, although I haven't looked deep enough to see if they are there.

Thanks so much. I should learn how to do this so I can contribute.

Mark

**Comment by obsbuddy** [comment]
And being able to map to Keyboard shortcuts like in Midi Key2Key, makes it possible to do some fantastic things like using midi keys to transition or cut.

**Comment by Alzy** [comment]
Adding LED feedback is specific per Midi controller. If anyone wants to give this feature a go, by all means do. Happy to merge it in if it works properly

**Comment by obsbuddy** [comment]
Can we map Transition, Quick Transitions, Transition Fader?
