### ISSUE TITLE
Feature request: Combined pause/resume recording, similar to start/stop recording.

### ISSUE THREAD

**Issue by MacGyverNL** [Alzy/obs-midi#52]
As the title says. Currently I need to map two buttons, one to pause and one to resume. Would be great to only have to spend one.

Funcionally this could even be combined with start recording, if the OBS API allows that, because you can't pause a recording that hasn't been started. So could have start/pause/resume on one button. Handy for the case where you don't plan on mapping the stop recording action to your MIDI controller anyway, but maybe that's asking for a bit much.

**Comment by cpyarger** [comment]
It is in the latest release, The action is called Toggle Recording  https://github.com/cpyarger/obs-midi/releases/latest
