### ISSUE TITLE
Launch OBS with plugin & Novation Launch Control connected causes OBS to hang in processes.

### ISSUE THREAD

**Issue by Blod722** [Alzy/obs-midi#53]
This is an issue i've been having for awhile now, no clue how to fix it, but i'll try my best to explain it. If needed, I can provide other details.

With this plugin installed, I plug in my Launch Control and start obs. OBS then does not open. When I try to open OBS again, it prompts me with "OBS is already running" and asks to launch anyway. I can launch OBS with no issues this time, however the OBS midi will not work, and I will be logged out of my twitch with none of my preferences saved.

When I first try and disable it, it'll stop using my GPU and CPU, but Task Manager will not let me fully close the process, When I try to it tells me Access is Denied. The process sits at about 36MBs of usage on memory every time this happens. I've also tried ending it via Powershell and it does not work, it'll stay stuck in my processes until I unplug my Launch Control, if I haven't already tried to disable OBS, it causes a crash. [Crash 2021-01-29 18-27-22.txt](https://github.com/Alzy/obs-midi/files/5896874/Crash.2021-01-29.18-27-22.txt). But if I already tried to disable OBS, it'll close no problem. OBS MIDI is the only non-default plugin I have installed.

I have gotten OBS Midi to work with my Launch Control before. I have no clue why, since I did everything the exact same and it has worked.

**Comment by cpyarger** [comment]
Take a look at the latest version of the plugin, old mappings will need to be deleted and readded 

the new release can be found here https://github.com/cpyarger/obs-midi/releases/latest

**Comment by Blod722** [comment]
I appreciate your work and I have got it to work properly! However, I will still run into the same issue noted in the original issue post if I start OBS with the Launch Control plugged in. But, if I start OBS with it unplugged, and plug it in after start up, it'll work no problem. Saved bindings and all.

**Comment by cpyarger** [comment]
very odd. I wonder if some other program is trying to use the launch control at the same time

**Comment by Blod722** [comment]
Hmm, is there anyway I can give that info to you? (Other programs running/trying to connect to a peripheral) Because I can't think of anything that might be trying to interact with it. Maybe Google Chrome, Razer Synapse, or some sort of 3rd Party Anti-Cheat (like FaceIT AC), but I'm not actively trying to use the Midi Device elsewhere.

**Comment by cpyarger** [comment]
Take a look at the latest release here, https://github.com/cpyarger/obs-midi/releases/latest and drop me an issue on that repo if you are still having the issue
