### ISSUE TITLE
OBS-Midi makes OBS crash

### ISSUE THREAD

**Issue by TheGamersCubeNL** [Alzy/obs-midi#61]
when i eneble the midi controller obs crashes
[Crash 2021-02-12 19-14-35.txt](https://github.com/Alzy/obs-midi/files/5973640/Crash.2021-02-12.19-14-35.txt)

**Comment by cpyarger** [comment]
I need a bit more information, What version of the plugin did you install? The latest version is here https://github.com/cpyarger/obs-midi/releases/latest Try giving that a go

**Comment by TheGamersCubeNL** [comment]
nope stil a crach when i eneble the midi device

**Comment by cpyarger** [comment]
Did you have the old release installed? I know that there are breaking changes between the old config file format and the new one, If you did you may need to delete the old config from your obs configuration basic.ini file

**Comment by zanna241** [comment]
HI. when i eneble the midi controller obs crasobs crash
[obs crash.txt](https://github.com/Alzy/obs-midi/files/6015401/obs.crash.txt)
hes

**Comment by cpyarger** [comment]
All known crashes are currently fixes in the latest releases at https://github.com/cpyarger/obs-midi/releases/latest
