### ISSUE TITLE
Toggle actions to not update buttons on MIDI control surface

### ISSUE THREAD

**Issue by jonathan-g** [Alzy/obs-midi#68]
Connecting a MIDI note-on signal from a button on a control surface to toggle mute on an audio source works to toggle the mute on and off, but the LED on the control surface button does not toggle its on/off state.

## Platform

Operating system and version: Windows 10 Pro, 64 bit version 20H2 build 19042.804
OBS Studio version:  26.1.1 64 bit

Hardware: Dual Xeon E5-2662, 64 GB RAM
MIDI control surface: AKAI MIDIMIX

## Expected Behavior

The LED on the button on the control surface should toggle on and off to match the mute state of the audio source.

## Current Behavior

The mute state toggles on and off, but the LED remains off

## Steps to Reproduce

1. Open OBS MIDI Settings
2. Select "Devices" tab
3. Select MIDI Mix 1 device.
4. Check "Enabled" and "Bidirectional"
5. Select "MIDI Mix 1" as the output for bidirectional
6. Select the "Configure Midi Mix 1" tab
7. Configure MIDI event for Channel 1, Message type Note on, Note/control 1, value 127 and map it to action Toggle Mute for an audio source.
8. Click "Add Mapping"
9. Push the button.
10. Mute toggles on and off, but LED does not change.

## Additional information

I observe that if I close the OBS MIDI Settings dialog and then open it again and go to the "Devices" tab, the Output for th eMIDI Mix bidirectional signal has changed to "Microsoft GS Wavetable Synth" If I reset this to "MIDI Mix 1", it remains at this setting as long as the dialog is open, but if I close the dialog and re-open it, the bidrectional signal output has reverted to "Microsoft GS Wavetable Synth" again. This may be the cause of the bug in updating the LEDs.

**Comment by cpyarger** [comment]
Current work is being done on the branch http://github.com/cpyarger/obs-midi 
The latest releases are currently at http://github.com/cpyarger/obs-midi/releases/latest

Try the latest release and drop an issue on that fork if you still are having issues.
